import { UnitConfiguration } from "src/models/stores/unit-configuration";

export const unitConfigDefaults: UnitConfiguration = {
  appName: "Test",
  pageTitle: "Test Page Title",
  demoProblemTitle: "Demo Problem Title",
  defaultProblemOrdinal: "1.1",
  autoAssignStudentsToIndividualGroups: false,
  defaultDocumentType: "personal",
  defaultDocumentTitle: "Untitled Document",
  docTimeStampPropertyName: "timeStamp",
  docDisplayIdPropertyName: "displayId",
  defaultDocumentTemplate: undefined,
  planningTemplate: undefined,
  defaultLearningLogTitle: "Default LL Title",
  initialLearningLogTitle: "Initial LL Title",
  defaultLearningLogDocument: false,
  autoSectionProblemDocuments: false,
  documentLabelProperties: [] as any,
  documentLabels: {},
  problemHierarchyLabels: {},
  disablePublish: [] as any,
  enableHistoryRoles: [] as any,
  enableCommentRoles: [] as any,
  copyPreferOriginTitle: true,
  disableTileDrags: true,
  showClassSwitcher: false,
  supportStackedTwoUpView: false,
  showPublishedDocsInPrimaryWorkspace: false,
  comparisonPlaceholderContent: "foo",
  initiallyHideExemplars: false,
  navTabs: {} as any,
  disabledFeatures: ["foo"],
  toolbar: [] as any,
  authorTools: [] as any,
  myResourcesToolbar: [] as any,
  placeholderText: "Placeholder Text",
  stamps: [] as any,
  settings: {},
  aiEvaluation: undefined,
  aiPrompt: undefined
} as UnitConfiguration;

export const unitConfigOverrides: UnitConfiguration = {
  appName: "New Test",
  pageTitle: "New Test Page Title",
  demoProblemTitle: "New Demo Problem Title",
  defaultProblemOrdinal: "9.9",
  autoAssignStudentsToIndividualGroups: true,
  defaultDocumentType: "problem",
  defaultDocumentTitle: "Untitled Problem",
  docTimeStampPropertyName: "dateStamp",
  docDisplayIdPropertyName: "displayIdName",
  defaultDocumentTemplate: undefined,
  planningTemplate: undefined,
  defaultLearningLogTitle: "New Default LL Title",
  initialLearningLogTitle: "New Initial LL Title",
  defaultLearningLogDocument: true,
  autoSectionProblemDocuments: true,
  documentLabelProperties: [] as any,
  documentLabels: {},
  problemHierarchyLabels: {},
  disablePublish: [] as any,
  enableHistoryRoles: [] as any,
  enableCommentRoles: [] as any,
  copyPreferOriginTitle: false,
  disableTileDrags: false,
  showClassSwitcher: true,
  supportStackedTwoUpView: true,
  showPublishedDocsInPrimaryWorkspace: true,
  comparisonPlaceholderContent: "bar",
  initiallyHideExemplars: true,
  navTabs: {} as any,
  disabledFeatures: ["bar"],
  toolbar: [] as any,
  authorTools: [] as any,
  myResourcesToolbar: [] as any,
  placeholderText: "New Placeholder Text",
  stamps: [] as any,
  settings: {},
  aiEvaluation: "custom",
  aiPrompt: {
    mainPrompt: "This is a picture of a student document.\n Please categorize it.",
    categorizationDescription: "The focus area of the document",
    categories: ["user", "environment", "form", "function"],
    keyIndicatorsPrompt: "List of main features or elements of the document that support this categorization",
    discussionPrompt: "Any other relevant information.",
    systemPrompt: "You are a teaching assistant in a middle school science class."
  }
} as UnitConfiguration;
