# Config file for Decap CMS
backend:
  name: github
  repo: concord-consortium/clue-curriculum
  branch: author # Branch to update (optional; defaults to master)
  base_url: https://us-central1-cms-github-auth.cloudfunctions.net
  auth_endpoint: /oauth/auth
# local_backend: true
media_folder: "images/uploads"
collections:
  - name: sections
    label: Curriculum Sections
    label_singular: 'Curriculum Section'
    identifier_field: 'type'
    format: json
    folder: curriculum
    # create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 6 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Type
        name: type
        widget: string
      - label: Content
        name: content
        widget: clue
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    meta: { path: { widget: hidden, label: 'Path', index_file: 'content' } }
