name: Release Production
on:
  workflow_dispatch:
    inputs:
      version:
        description: The git tag for the version to use for index.html
        required: true
jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ inputs.version }}
      dest-file: index.html
    secrets: inherit
