name: Release Staging
on:
  workflow_dispatch:
    inputs:
      version:
        description: The git tag for the version to use for staging.html
        required: true
jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ inputs.version }}
      dest-file: staging.html
      environment: staging
      url: https://collaborative-learning.concord.org/staging.html
    secrets: inherit
